### PR TITLE
Removing Types from Ref Emits #17.

### PR DESCRIPTION
**Pull request by Mike-EEE**
As discussed in #17.

### CODE REVIEW

**Comment by Mike-EEE** [comment]
Ahhh... yes, I am going by those tests passing, so if something doesn't work we should introduce new tests instead of modifying new ones. :)  I have checked in a fix.  Hopefully it works!

**Comment by wojtpl2** [comment]
I'll remember. You have to change a few xml because they still don't pass tests. 

Tomorrow I'll create branch v2.0.
I have plan about new configuration. But my changes break current configuration method.

**Comment by Mike-EEE** [comment]
Ugh weird!  [It works on my machine](https://rlv.zcache.co.uk/works_on_my_machine_round_sticker-r56ce1cc314be46efbe749e9c58c761d5_v9waf_8byvr_512.jpg). :P   I will look into this and get another commit.

And yes, hopefully once you get that new branch up I will have a monstrous PR for you. :P  All new code.  I'm really ashamed it has taken so long!  But it has been fun.  If you don't like it I at least have some cool new serialization tricks. :)

**Comment by Mike-EEE** [comment]
Oh I see.  The XML was not checked into your master.  I am still new to Git and learning a lot.  This project is a good experience. :)  This PR is also out of my master, which I am learning is not a good thing to do. :/

**Comment by Mike-EEE** [comment]
Ah I see the problem.  The references are being stored by type ID, when really they can be stored by a unique ID altogether.   `ref="[id]"` should really be `ref="[typename]_[id]"`.  This would introduce a breaking change, however.  If you are OK with that, I could continue.  Otherwise, I am starting to feel that I have put too much time into this and would rather focus on my efforts on v2.0 instead.

**Comment by Mike-EEE** [comment]
Boo, apparently there is a conflict now.  Not doing well today. :P  Although that should fix the tests now.  I have also added tests for the concrete classes as well.

**Comment by wojtpl2** [comment]
I wanted to do migration for inheritance. But I have a problem.
Currently in xml we have:
<node type="A" ver="1">
and e.g.:
class A : B,
class B : C

and if we have migration for A, B and C e.g.:
A has 2 migration - ver="2"
B has 1 migration - ver="1"
C has 1 migration - ver="1"

and of course user can add other migration for any type in the future.
I don't have idea how xml should look for this situation in case we want run migration from base type in current type. And what order to run migrations if user can add migration migration in order e.g. C,A,B,A. And we should deserialize all old xml.

Do you have any idea or do you think it is wrong way?

**Comment by wojtpl2** [comment]
Thanks!

**Comment by Mike-EEE** [comment]
Ah I see.  Is this for the current merge?  Or existing code?  If this is for the current merge we can discuss here.  If this is a general question for code, let's open a new issue and discuss there.  My concern now is that the build is breaking?  It is saying that 1 check is failing.

I think for Migrations you will have to break it out in steps or slices.  I will have to think about it. :)

**Comment by wojtpl2** [comment]
I've merged your code. This questions was about my problem. 
Ok I'll create issue version 2.0.

**Comment by Mike-EEE** [comment]
OK great, Open it there and we can discuss. 👍

**Comment by wojtpl2** [comment]
I've also published version 1.5.0 with you changes ;)

**Comment by Mike-EEE** [comment]
Sweeeeeeet.  I finally got my code working yesterday.  I just now have to round out some tests and I'll be ready for that mega-PR for you. :o

**Comment by wojtpl2** [comment]
I've added information about you in codeproject. 
You can look: https://www.codeproject.com/Articles/1121574/Extended-XML-Serializer-for-NET

**Comment by Mike-EEE** [comment]
Haha oh boy I am no longer an anonymous dev. :P

**Pull request merged**
