### PR TITLE
Feature/references

### PR DESCRIPTION
**Pull request by Mike-EEE**
Goodness!  This took wayyyyyyyyy too long, with the performance issues and just getting it to work.

We now have basic references support.  Please see `ReferencesExtensionTests` for examples.

I haven't gotten around to hashing the values yet, and I ended up splitting the two scenarios (identities and entities) into different properties.  I also still need to do a check before writing to see if there are any references detected without the `ReferencesExtension` enabled.  If there are, it will throw with a message to enable the extension.

Anyways, please review and provide any feedback.  Please merge if it looks OK. 👍

### CODE REVIEW

**Comment by Mike-EEE** [comment]
Oh, I forgot to mention:  I try to stay away from dependency injection these days but i ended up in a service provider implementation for the configuration setup.  I ended up going with the simplest (and fastest) container I could find and ended up with LightInject: https://github.com/seesharper/LightInject

It's only used for the extension model and is not exposed to consumers.  I made a [wrapper class](https://github.com/Mike-EEE/ExtendedXmlSerializer/blob/feature/references/src/ExtendedXmlSerializer/ExtensionModel/Services.cs) that serves as the integration point.

Please let me know if this is a problem.  I know a lot of people might see a dependency on an IoC library and get nervous.  I basically wanted to include it so that I didn't have to write a bunch of code and reinvent yet another wheel.  Also, the [`Decorate`](https://github.com/Mike-EEE/ExtendedXmlSerializer/blob/feature/references/src/ExtendedXmlSerializer/ExtensionModel/Services.cs#L135-L136) method is exactly what I was looking for (and was the sticking point for when I started to look around for other solutions).

**Comment by Mike-EEE** [comment]
So doing some research, looks like I was way off on my understanding of hash/hashing.  As you will recall I was thinking of doing something like `id="ceXErs"` or something of that nature.  I was thinking of bit.ly's short URLs.  Basically what I *was* thinking of was actual hashing which would be the encryption that you already have. :)  

Additionally, we are using `uint`s for generated IDs, so they look like `identity="1"`, which is much sorter and concise (less required space).  I think what we have now works for v2. 👍

**Comment by wojtpl2** [comment]
I don't have enough time to read everything 😉 
image

All tests are passed.

I have 2 question:

**1. After build we have 5 dlls.** 
image
I wonder what if user will use eg LightInjection in different version? 

**2. Configuration API**
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/test/ExtendedXmlSerializerTest/ExtensionModel/ReferencesExtensionTests.cs#L221-L233
Is it test your private (internal) API? Or is it API for user? 

I think it is private API and all configuration should be do by fluent API. In this case all your api should be private or internal eg:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/src/ExtendedXmlSerializer/ContentModel/Members/MemberDescriptor.cs#L29

Only configuration and interface for serializer should be public. Or maybe it will be part of configuration?

**Comment by Mike-EEE** [comment]
Hahaha... yeah, I get carried away.  Hopefully there won't be too much more of that. 👼 

As for your questions...

1. That's a good point.  That dll might be placed in the bin, but if you look in the actual DLL where it is used, you will not see it referenced.  So it will be emitted into the /bin/ but it is not required for NuGet/packaging.

2. Ah!  I forgot to mention this as well.  Yes, that is all what the ConfigurationAPI in meant to work with, so what you see there is a very rough "just get it to work" approach, and NOT how the ConfigurationAPI will look like.  Configuration API is next after I get the extensions.  Hopefully after this week. 👍 

3. (Yes, I should go through and make sure everything is internal).  I will make an issue for this.

**Comment by Mike-EEE** [comment]
OH... and for the different LightInject versions... yes, this would be a risk, as with any dependency we take on.  The same would go for Sprache, or even .NET Core assemblies.  Although there might be some configuration we could apply that would ensure/enforce a particular version.  I am definitely open to options/considerations/feedback here.

**Comment by wojtpl2** [comment]
It will be a great challenge abandon these additional libraries?

**Comment by Mike-EEE** [comment]
:/ Yeah... well, that's a good question.  My first thought is, if you think we have a lot of code already, then wait until you see after we remove these libraries.  

But thinking about it more, we *could* replace it with our own, simpler implementation.  Obviously, by leveraging those libraries, we gain all their testing, maturity and reduce risk.  I didn't want to spend a bunch of time (after already having spent enough!) writing implementations and then fixing all sorts of bugs around them (as I have done in the past).

So maybe we keep them in now, and at some later point we could implement our own simpler implementations that do the same thing?  I am not sure I would be the one writing them, however. 👼 

(The worst experience is to encounter a bug that is already solved and fixed in another library.)

**Comment by wojtpl2** [comment]
LightInject you can install source directly to our project :wink:
Install-Package LightInject.Source 

http://www.lightinject.net/#installing

**Comment by Mike-EEE** [comment]
Well how about that! :)  That takes care of one of them.

**Comment by Mike-EEE** [comment]
Technically we could do the same w/ Sprache, and just copy the code directly into the project.  Would that work for you?

**Comment by wojtpl2** [comment]
We can do this by git submodule. But I don't have great memories of it.

**Comment by Mike-EEE** [comment]
Ewwww... yeah, neither I.  There's also subtree which I think is supposed to be better?  Git doesn't like me too well. :P  But I think in this case it will be worth it.

**Pull request merged**
