### PR TITLE
Issues/35

### PR DESCRIPTION
**Pull request by Mike-EEE**
I was able to address #35 and get performance back to v1 levels.  However Benchmark.NET is being a little flaky with me.  Sometimes the serializer is actually FASTER than v1, but the deserializer will end up being slower.  And then vice versa.  If you try 5ebffd5 it is pretty consistent with its results.  Here is an example on my machine:

```
                            Method |       Mean |    StdDev |  Gen 0 | Allocated |
---------------------------------- |----------- |---------- |------- |---------- |
   SerializationClassWithPrimitive | 72.9432 us | 0.1259 us | 5.9570 |  44.55 kB |
 DeserializationClassWithPrimitive | 97.9249 us | 0.1584 us | 7.1615 |  63.93 kB |
```

I did some design improvements with 7a1918c but the flaky results came along with it.  So anyways, it is much more like v1 now, but probably not as consistent as I would like (but it might just be my machine).

Getting this submitted so we can discuss (and also for you to try out!).

### CODE REVIEW

**Comment by Mike-EEE** [comment]
Here's a good example of "fast for one but not the other" on 7a1918c:

```
                            Method |        Mean |    StdDev |  Gen 0 | Allocated |
---------------------------------- |------------ |---------- |------- |---------- |
   SerializationClassWithPrimitive |  71.7722 us | 0.3069 us | 5.9570 |  44.55 kB |
 DeserializationClassWithPrimitive | 107.6939 us | 0.0845 us | 7.1615 |  63.93 kB |
```

Spent way too much time trying to figure this out.  Not even sure if it's an issue.  If you have any insights I am more than happy to hear them.

**Comment by Mike-EEE** [comment]
FWIW I am taking another look at this now.

**Comment by wojtpl2** [comment]
Ok I'm waiting.

**Comment by Mike-EEE** [comment]
Kaboom!

```
                            Method |       Mean |    StdDev |  Gen 0 | Allocated |
---------------------------------- |----------- |---------- |------- |---------- |
   SerializationClassWithPrimitive | 72.5647 us | 0.1049 us | 6.1361 |  45.14 kB |
 DeserializationClassWithPrimitive | 97.5676 us | 0.3249 us | 6.5104 |  63.93 kB |
```

:)

There were a few allocations from ImmutableArray that were being boxed and it was not happy with that.  Looks like we are just as good if not better than v1 now.  Please verify on your machine and merge if it looks OK.

**Comment by wojtpl2** [comment]
Ok, I'll try.

**Comment by wojtpl2** [comment]
You're right. Serializer V2 is a little better than V1. 
Serializer V2 uses less memory than standard Serializer! It is really good achievement.
Desierializer is still worse.

.NET 4.5
```
#0 ExtendedXmlSerializerTest
                            Method |        Mean |    StdDev |   Gen 0 | Allocated |
---------------------------------- |------------ |---------- |-------- |---------- |
   SerializationClassWithPrimitive |  80.8440 us | 1.2415 us | 21.5007 |  51.33 kB |
 DeserializationClassWithPrimitive | 110.5328 us | 1.3932 us | 21.8099 |  55.98 kB |
 
#1 ExtendedXmlSerializerV2Test
                            Method |        Mean |    StdDev |   Gen 0 | Allocated |
---------------------------------- |------------ |---------- |-------- |---------- |
   SerializationClassWithPrimitive |  79.8060 us | 0.2296 us | 19.0755 |  45.18 kB |
 DeserializationClassWithPrimitive | 114.7688 us | 2.1352 us | 25.3255 |  63.93 kB |
 
#2 XmlSerializerTest
                            Method |       Mean |    StdDev |   Gen 0 | Allocated |
---------------------------------- |----------- |---------- |-------- |---------- |
   SerializationClassWithPrimitive | 64.3667 us | 1.1229 us | 24.4466 |  56.85 kB |
 DeserializationClassWithPrimitive | 70.9351 us | 1.1366 us |  8.1380 |  22.91 kB |
```
 
.Net Core
```
#0 ExtendedXmlSerializerTest
                            Method |      Median |    StdDev |
---------------------------------- |------------ |---------- |
   SerializationClassWithPrimitive | 121.7234 us | 2.2336 us |
 DeserializationClassWithPrimitive | 116.9649 us | 1.8517 us |
 
#1 ExtendedXmlSerializerV2Test
                            Method |      Median |    StdDev |
---------------------------------- |------------ |---------- |
   SerializationClassWithPrimitive | 117.4570 us | 2.0138 us |
 DeserializationClassWithPrimitive | 114.7262 us | 1.8112 us |
 
#2 XmlSerializerTest
                            Method |     Median |    StdDev |
---------------------------------- |----------- |---------- |
   SerializationClassWithPrimitive | 91.9608 us | 1.9419 us |
 DeserializationClassWithPrimitive | 71.7313 us | 1.0443 us |
```

**Comment by Mike-EEE** [comment]
Horray.  Yeah it's hit and miss.  Just depends on the CPU cycles and whatnot, but it's definitely in the area now, if not a smidge faster.  Could probably make it a little faster if I knew more about memory management.  Benchmark.NET is a good way to do so. 😎 

In any case, glad it didn't have anything to do inherently with my design. 👍  😌

**Pull request merged**
