### PR TITLE
v2.0 Serializer Candidate

### PR DESCRIPTION
**Pull request by Mike-EEE**
Wow. :)  I think I mentioned it already, but I am quite embarrassed with myself and how much time I put into this.  However, there's a lot of new functionality that I think you will appreciate.  There's a LOT to cover here, so I will try to keep it concise.

**TL;DR:**  Check out the [`FuturesTest`](https://github.com/Mike-EEE/ExtendedXmlSerializer/blob/Write/test/ExtendedXmlSerializerTest/FuturesTest.cs) file to see tests that run through all the new features.

What I've done is basically took your extensibility model and took it up a notch.  There is a notion of an [`IExtension`](https://github.com/Mike-EEE/ExtendedXmlSerializer/blob/Write/src/ExtendedXmlSerializer/Extensibility/IExtension.cs) that allows you to add your extensions to the serializer.  Your previous configuration extensions can be seen in its [new incarnation here](https://github.com/Mike-EEE/ExtendedXmlSerializer/blob/Write/src/ExtendedXmlSerializer/Write/Extensibility/DefaultWritingExtensions.cs).  

Please note that I took a lot of time to ensure that v1.0 functionality operates as expected.  In fact, there is now the notion of [`ISerializationProfile`](https://github.com/Mike-EEE/ExtendedXmlSerializer/blob/Write/src/ExtendedXmlSerializer/Profiles/ISerializationProfile.cs) that can be used to create your own serializer from scratch.  This will allow tremendous flexibility going forward to create profiles based on versions.  I have [created a v2.0 profile here](https://github.com/Mike-EEE/ExtendedXmlSerializer/blob/Write/src/ExtendedXmlSerializer/Profiles/SerializationProfileVersion20.cs), with the intent of keeping any modifications made there away from v1.0 (or 3.0, etc. :)).  Currently they use the same base class, but that can be easily broken out.

So to wrap all the new features, check out [`FuturesTest`](https://github.com/Mike-EEE/ExtendedXmlSerializer/blob/Write/test/ExtendedXmlSerializerTest/FuturesTest.cs) that goes through about 8 tests that demonstrate the new behavior.

You can see a few things here:

- Capability for Auto-properties and `XmlAttribute` (#6).  I have it configured in the `VerifyAutoAttributes` and `VerifyAutoAttributesWithLongContent` test to emit all primitive types as properties/attributes, and emit strings as content/element if it goes over 128 characters.
- Attached Properties.  I think this is kinda cool.  But thinking how we were talking about #12, well, `exs:type` happens to be... tada! An attached property.  So, I have that in there now.
- Lists with properties.  This addresses #7 
- Default values.  This is totally customizable now.  You basically can use specifications to say when to emit a property or not.
- Extensions.  I demonstrate how to tap into the emit pipeline to change values of a list, as an example of an extension.  I also provide an example of how to skip elements in the pipeline as well.

There's a lot lot more.  Again it's totally fine if this is too much LOL.  I went overboard what can I say.  I still need to do the reader.  It should take another week or so.  But once it is done, it's done!  Please let me know your thoughts and we will take it from there. :)

### CODE REVIEW

**Comment by wojtpl2** [comment]
I need time to check all changes. But looks amazing! Big effort. Thank!

But I see that you create CustomExtendedXmlSerializerConfig for inheritance. It's not good because now ExtendedXmlSerializerConfig works fine only for ObjectReference and Encrypt, But not works fine for CustomSerializer and Migration. Of course in case inheritance.

I'm worried about performance too, but I'll check it.

**Comment by wojtpl2** [comment]
For now I've only checked:
1. Project ExtendedXmlSerializer.Samples not work for both .Net4.5 and .NET Core.
2. If you build project by script build.ps1 you will see that test not passing form .net core. The .Net core has different CoreLib. In BaseTest you can see how to work around this problem. 
3. Performance isn't good:
For .net core test not work (I don't know why). For .net 4.5:
```
Type=ExtendedXmlSerializerTest  Mode=Throughput

                            Method |        Median |     StdDev |
---------------------------------- |-------------- |----------- |
   SerializationClassWithPrimitive | 2,181.8347 us | 70.7013 us |
 DeserializationClassWithPrimitive |   126.0302 us |  7.0666 us |
                                  
                                                                      
 Type=XmlSerializerTest  Mode=Throughput                              
                                                                      
                             Method |     Median |     StdDev |       
 ---------------------------------- |----------- |----------- |       
    SerializationClassWithPrimitive | 53.0441 us |  1.8241 us |       
  DeserializationClassWithPrimitive | 82.9184 us | 11.3939 us |       
```
Standard serializer has 53.0441 us, ours has 2,181.8347 us. It is too mach.

But functionality looks amazing! 
My description will be continued ...

**Comment by Mike-EEE** [comment]
Yeah, it's a little more involved now and I was going to get into the performance.  At 2 full seconds, though?!  That seems a little high.  I was expecting some overhead but that seems a little much.  I will look into it.

I am also working in 4.5. :)  I haven't really gotten into .NET Core yet and I am not a fan of those compiler directives. :P  I will look into it, however.

Also, for `CustomExtendedXmlSerializerConfig`.  Blah.  That is a merge booboo.  I had that merged from my branch and didn't know how to undo it in my local branch.  I will try to get that reverted manually.

**Comment by wojtpl2** [comment]
OK. And I have one more question. Do your changes support migration, custom serialization, object reference and encryption?

**Comment by Mike-EEE** [comment]
Yes, all the previous scenarios work, as you will notice I didn't touch any of the tests. :)  So all v1.0 features are still supported and work exactly as before, they are just super slow. 😮

**Comment by wojtpl2** [comment]
I understend that v1.0 features works with migration. But I ask you about version 2.0?

**Comment by Mike-EEE** [comment]
Oh!  Yes, yes they do. :)  [It's sort of hard-coded in there right now](https://github.com/Mike-EEE/ExtendedXmlSerializer/blob/Write/src/ExtendedXmlSerializer/Profiles/SerializationProfile.cs#L97-L100), but both profiles use the same extensions.  I didn't write any tests around this, however.  I wanted to get this checked in and the conversation started before figuring out how much more time to spend on this. :)

**Comment by wojtpl2** [comment]
Ok. For me your changes looks fine and I see your hard work. But I need more time to read all - and understand it :).

But for first look I don't understand idea of profiles. Why don't you use configuration or something like that:

new Serialization( new Config() {useAutoProperties=True});
or maybe I didn't read correct yet.

**Comment by Mike-EEE** [comment]
Yeah again it is a lot, and I am honestly OK with ditching it all and throwing it all away, because it is so much.  It basically is how I would write a serializer, and it allows the user to have full control/customization of how it writes (and eventually reads -- if I get to it) an object.  I might have gotten a little carried away. 👼 It didn't start like that, but ended like that haha.

The `SerializationProfile` object is a stab at configuration.  We could conceivably wrap it in (or even replace it with) a configuration object.  I wanted a way to cleanly separate out versions and how serializers are built.  Initially, I did have an `AutoPropertiesExtension`, but then it simply turned into a specification, so that is what is passed in now.  We could conceivably make it an extension (which is then added when you set "AutoProperties=true" as above), if that would make it easier to work with and understand.

**Comment by wojtpl2** [comment]
Your changes will be used in version 2.0. I'll approve this changes on branch v2.0 when you fix above problems. It is good start!

I asked you about this things, becouse I think about users and about documentation. If configuration will be difficult to understand users won't be use this library. And of course we have to create documentation for it. Without it we can't publish it even we solve other problems.

**Comment by Mike-EEE** [comment]
Hey thanks for that.  So, I have put some thought into this, and there are some considerations that I haven't thought of, such as performance and documentation.  I am finding more barriers here than not.  So here is my list:

Pros:
- Very flexible design (probably too flexible)
- Fixes some known issues in the repo.
- Extension-based framework

Cons:
- Performance (will take some time, could be part of the design).
- Documentation (I am not very good at this and I have introduced **a lot** to document.
- Very different from 1.0.
- Doesn't have very straight-forward configuration.
- Still doesn't have a deserializer (will probably take another week or so).
- Doesn't work in .NET Core (I am not familiar with this so this will take some time)
- Merging problems (with `CustomExtendedXmlSerializerConfig`)
- Took a lot of time (I was thinking it would take the weekend and it took two weeks!)

I wanted to get this committed and available to you first and then reflect on next steps.  My feeling at this point is that this change while compatible with v1.0 is _too different_ and might be too much of a commitment on your part.  With the amount of work left, I am thinking/feeling that I should cut my losses and leave this here with you.  I do have other commitments that I need to attend to and they have been neglected with my efforts here haha.

That is not to say that all is lost.  If you find something in here you like, please feel free to use it.  There is definitely some cool stuff in here that I might use in my own projects going forward as well. :)  

Sound OK?

**Comment by wojtpl2** [comment]
It is your choice ;) Do you want create deserializer or no longer?

**Comment by Mike-EEE** [comment]
Haha!  Tempting. :)  I don't know, lemme think about that.  I feel bad for giving you a half-baked solution.  If I did, it might be slooooooooow though, and wouldn't be 100% complete (like the serializer is now).  Would you be OK with that?

**Comment by Mike-EEE** [comment]
Alright I have fixed the Samples in 4.5,  Please ensure it works in .NETCore as well.  It would be nice to make sure there are tests that mimic this behavior to be sure going forward. :)

**Comment by Mike-EEE** [comment]
Bummer... the only way I can profile and see what the bottleneck is through dotTrace, and ReSharper Ultimate doesn't support .NETCore in the current version. :(  However, the version they are working on now does.  It should be done soon.  I could start working on the deserializer and maybe it will be done then. :P

**Comment by Mike-EEE** [comment]
Alright so there were two performance issues that I found.

1. The results of calling services weren't being cached.
1. Extensions are unfortunately very slow.

I was able to shave off about a second from that nasty performance time.  On my machine it was clocking at 2,600us (!).  Now it clocks in at around 1600..  However, if I comment out the extensions it drops down to 500us. 😮 

So there's a problem there.  I am not sure the best way to speed it up.  Essentially what happens is that for every write state on every element, all registered `IExtension` get called.

Here's the breakdown of write states:

```
- Root
	- Instance
		- Members
			- Member (Starting/entering member)
		        - MemberValue (Writing the value of the member)
```

Hope that makes sense.  So right now each state on each member is getting called and it is slowwwwwww.  It could definitely stand for some improvement.  I am just not sure how at this point.

**Comment by wojtpl2** [comment]
Thank you. I'll check all changes in monday. I try don't work at weekend.

I'll try optimize your code.

**Comment by Mike-EEE** [comment]
Hah!  No worries, you are the smarter of us two. 😛  I have a few ideas now and will try to apply them.  I am also warming up to that deserializer. Ha ha.  Have a nice weekend!

**Comment by wojtpl2** [comment]
I have the result 1,002.2541 us on my computer. It is good progress!
I approve this and then I can do something.

**Comment by wojtpl2** [comment]
I've added you permission to do push directly to repo.

**Comment by Mike-EEE** [comment]
OK cool. :)  Thank you!  I will use responsibly. 👼

**Pull request merged**
