### PR TITLE
Attending to open issues.

### PR DESCRIPTION
**Pull request by Mike-EEE**
This PR is intended to address open issues in the repo.  Additional commits will be performed and then accepted when issues are completed.

### CODE REVIEW

**Comment by wojtpl2** [comment]
Can I accept this PR? Or do you still work on it?

**Comment by Mike-EEE** [comment]
Ah I was going to do #70 and #71 before doing so, but this is a good place to merge.

**Comment by Mike-EEE** [comment]
You know it just occurred to me that since I have contributor rights, that I don't need to PR, do I?  I could link directly to this repo and push directly, correct?  I can still do PRs if that makes more sense, as well.

**Comment by wojtpl2** [comment]
You can push directly. I don't have problem with it ;) for me you are author of version 2.

**Comment by Mike-EEE** [comment]
Haha... yeah, I guess I kind of am. :P

**Pull request merged**
