### PR TITLE
Improvement/performance

### PR DESCRIPTION
**Pull request by Mike-EEE**
Woohoo... I got some serious performance improvement that this PR introduces.  Check it out:

```
// **************************
// Benchmark: ExtendedXmlSerializerTest.DeserializationClassWithPrimitive: DefaultJob

                            Method |       Mean |    StdDev |  Gen 0 | Allocated |
---------------------------------- |----------- |---------- |------- |---------- |
   SerializationClassWithPrimitive | 74.2877 us | 0.9071 us | 7.0475 |  51.17 kB |
 DeserializationClassWithPrimitive | 97.5923 us | 0.2960 us | 5.4362 |  55.97 kB |

// **************************
// Benchmark: ExtendedXmlSerializerV2Test.DeserializationClassWithPrimitive: DefaultJob

                            Method |       Mean |    StdDev |  Gen 0 | Allocated |
---------------------------------- |----------- |---------- |------- |---------- |
   SerializationClassWithPrimitive | 33.4268 us | 0.0900 us | 4.9886 |  32.77 kB |
 DeserializationClassWithPrimitive | 44.6563 us | 0.0863 us | 3.4912 |   25.6 kB |

// **************************
// Benchmark: XmlSerializerTest.DeserializationClassWithPrimitive: DefaultJob

                            Method |       Mean |    StdDev |  Gen 0 | Allocated |
---------------------------------- |----------- |---------- |------- |---------- |
   SerializationClassWithPrimitive | 62.1980 us | 0.0671 us | 8.2031 |  56.85 kB |
 DeserializationClassWithPrimitive | 67.9054 us | 0.2292 us | 2.7832 |  27.32 kB |
```

I got this improvement by caching the primitive results (anything using `XmlConvert.*`.  Since any data that is used for these conversion is considered a constant (e.g. the string `"12.10004"` will _always_ result in a double/float/etc of `12.10004`), then this makes sense to do.  However, in case there are problems, or if someone wants to turn this off, this is supported.  We will have to add a method to the ConfigurationAPI that allows for this (maybe a `EnablePrimitiveOptimizations(bool)`).

### CODE REVIEW

**Comment by wojtpl2** [comment]
ok I'll check it today. 
Performance now is incredible! 🥇

**Comment by wojtpl2** [comment]
I see that in code is still XmlConvert. I don't know if I should add EnablePrimitiveOptimizations(true) or not? Or maybe do you added this?

**Comment by Mike-EEE** [comment]
Hey thanks. :D  Very happy with how this is turning out.  As for `EnablePrimitiveOptimizations`... I didn't add it, but was saying that we need to put one in if we want to disable it.  If you want to put it in the ConfigurationAPI I will wire it up when I am going through. 👍

**Comment by wojtpl2** [comment]
Ok. If we disable it (in configuration):
1. How will xml look?
2. What will you use for serialization of primitive version. I'm asking because XmlConvert generates the same xml for different regional settings (cultures).

**Comment by Mike-EEE** [comment]
So to be sure here, the only thing that this does it cache the results and stores it in a dictionary.  So if you ask for the `float` `3.14159`, it pulls it from the dictionary rather than asking `XmlConvert.ToSingle`.  Same with the other way as a string, and for all the primitives.  So, in theory, the XML should look the same.  However, I am not 100% on that, so that is why I think we should enable the ability to turn it off if necessary.  Also, if you have billion numbers those will all be stored in memory until the serializer is GC'd, so that is nice to prevent, too. :)

**Pull request merged**
