### PR TITLE
Possible Design Change for Specifications

### PR DESCRIPTION
**Pull request by Mike-EEE**
As discussed in #9, possible design change to address the current badness.  This request is just for your convenience and review, and is not expected to be merged (unless you like it, of course. 😄).

### CODE REVIEW

**Comment by wojtpl2** [comment]
It is a simple solution, but I think it isn't the best solution. I don't have idea how it should look at this moment. I have to think about it. I know only that without breaking changes we can't do this. Therefore, we can do something ambitious.

**Comment by Mike-EEE** [comment]
> Therefore, we can do something ambitious.

WAYYYYYYYYYYY ahead of you.  😛   I actually feel really bad with how much time I've been spending on this.  This has taken WAYYYYY longer than I expected.  I am getting tests to pass now though.  I was hoping to do both serializer and deserializer and then do a PR for review, but it looks like I will do the serializer first and then do a PR off of that to get the conversation started.

BTW, you might want to make a v2.0 branch. 👼

**Comment by wojtpl2** [comment]
You should create other PR for other changes. Right now I can't approve anything. By the way I think there is an easier way to do second commit. 
Can you check if we can do like this (it is pseudocode):
forceSaveType: propertyInfo.**CanWrite** &&propertyInfo.TypeDefinition.FullName != defType.FullName
In file ExtendedXmlSerializer line 501.

Version 2.0 sounds great. But we should do many things.
* Create configuration that works fine for inheritance in all situations. 
* Support XmlAttributte
* Add the ability to changing name (order ...) to the configuration without XmlRoot, XmlElement and XmlAttribute. 
* Namespaces for type, ver ... (it is your idea)
* Serialization class that inherits from IList, ICollection with additional properties enhancement

It is big job and we need plan for it.

**Comment by wojtpl2** [comment]
Sory for my comment :( I didn't see well what you did. You did it great. I'll try approve your changes from the last commit.

**Comment by Mike-EEE** [comment]
Haha no worries!  I figured you'd see it eventually.  And btw what I am working on will address each of those points above -- or should. 😛

**Comment by wojtpl2** [comment]
I think that first and third points should be do by one person. This is big change and I can do it in next week. Unless you have done something?

What points would you like to do ? If you wont?

I approved last commit. Big thanks!

**Comment by Mike-EEE** [comment]
Ah yes... if it is `ISerializationToolsFactory`-related then that makes more sense for you to handle.  I have built an extension mechanism around the serializer and have created integration points for `ISerializationToolsFactory`.  I am almost done with the serializer.  I have most tests passing and should be done later today for you to check out.  I will probably create a new branch on my fork this so you can see.

**Pull request closed without merging**
