### PR TITLE
Feature/deserializer

### PR DESCRIPTION
**Pull request by Mike-EEE**
OK!  Here is a v2 candidate for serializer and deserializer.  All tests pass and the samples project works, but it is a little slower now vs. legacy benchmarks (20us for serializer and 100us for deserializer).  Some notes:

1. Legacy folder is kind of a mess.  I intend to seal the classes and sort of lock the key there. :P
1. There is a lot of code to make the legacy stuff work as expected (passing tests).  This might be the reason why performance is slow.  I am pretty certain that a v2 (non-legacy) serializer/deserializer will be faster.
1. There are still a couple of model changes I want to make, so I will attend to those now and add those commits to this PR.  You can choose to merge now or wait until I have changes  I wanted to get this to you so you didn't feel blocked.

That's it, hope this all looks OK to you.  Please let me know if you have any questions and/or concerns.

### CODE REVIEW

**Comment by Mike-EEE** [comment]
Alright, I went through and made the model construction a bit simpler with the use of selectors/options.  There's a little more work to do, however.  Not too much... maybe about a day or so at the most.  Getting close. :)

**Comment by Mike-EEE** [comment]
Ah dang... I still have some more commits around this that I am working on.  Glad you merged it though!  I hope to send you some more commits by end of day today.  I'll merge them myself since you approved this one personally.

Be aware that these commits technically involve breaking changes as I organized the namespaces a bit to make the a little flatter/cleaner.  Hope that is OK. :)

**Comment by wojtpl2** [comment]
I have changes. I remove old configuration and add new API. This configuration will be better. You will have to do marge. I'll to push today. 
Probably not all project will be compiled. I think that tests should work.

**Comment by wojtpl2** [comment]
I have new configuration API, but I have little trouble with push. It can me take about 20 minutes.

**Comment by Mike-EEE** [comment]
Ok great!  Wow that was quick. :)  I am here on standby if you need any help. 👍

**Comment by Mike-EEE** [comment]
I was going to say that I can post my changes and send a PR if there are no conflicts, and then merge otherwise, but that was before your new message here.  I will wait for your push.

**Comment by wojtpl2** [comment]
I've pushed my changes. 
Currently I've removed form solution:
ExtendedXmlSerializer.AspCore,
ExtendedXmlSerializer.Autofac - I don't know if this project is still needed,
ExtendedXmlSerializer.WebApi,
ExtendedXmlSerializer.AspCore.Samples.
We'll manage this when we'll finish all changes.

I left in the code one place to change for you.
           //TODO for Michael DeMond connect to new serializer (andremove old?)
            Converter = this._config != null ? new LegacyRootConverter(this._config) : Defaults.Root;

**Comment by Mike-EEE** [comment]
Cool.  thank you.  I will check this out.  Are you removing those projects because they are no longer valid?  Or add unnecessary complexity?

As for the //TODO.  That circles back around to #30.  Right now the codebase has 3 serializers:

1. v2 (no functionality built around this yet, but should be very easy to do).
1. v1 with `ISerializationToolsFactory` (LegacyRootConverter).
1. v1 without `ISerializationToolsFactory` (Defaults.Root).

This is a LOT of unnecessary code.  If we do #30, then 2 and 3 go away, and we just have one serializer and this simplifies things GREATLY (it also saves me a ton of time).

From looking at your commit, this is a breaking change:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/src/ExtendedXmlSerializer/ExtendedXmlSerializer.cs#L42-L47

Unless you add another constructor, those who have used v1 with `new ExtendedXmlSerializer(new SimpleSerializationToolsFactory())` will break when they upgrade to v2.  Make sense?

Are you aware and OK with this?  If so, then we can do #30 and simplify.  Otherwise we will have to discuss.

**Comment by wojtpl2** [comment]
Of course, I haven't done all of things from new API, but I cover all current features.

I remove it because I'm not sure that project ExtendedXmlSerializer.Autofac is still needed. Project for WebApi and AspCore will be added but not now. When we will add all new function I'll implement integration. 

I think we don't need point 2 and 3. We need only v2. But look there:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/src/ExtendedXmlSerializer/NewConfiguration/IExtendedXmlSerializerConfig.cs#L6-L7
Version 2 should create xml with/without Namespaces and AutoProperties. I'm not sure if you understand me. We need one version of serializer/deserializer with all features.

**Comment by wojtpl2** [comment]
In the future, probably we will change namespace NewConfiguration. I've created this namespace because we have "Configuration" directory now.

**Comment by Mike-EEE** [comment]
Right!  No, I understand you. :)  That is my expectation, too.  Well, OK then.  Should I do #30 and remove `Legacy` namespace?  It will be a **lot** cleaner.

And yes, please delete Configuration and replace it with your new work. :)

**Comment by Mike-EEE** [comment]
Also, just to be 💯% sure...

> We need one version of serializer/deserializer with all features.

with all _v2_ features, correct?  v1 "features" are considered removed (replaced with v2 equivalent) and are breaking changes if you have code written as such.

**Comment by wojtpl2** [comment]
If you have code written with version 1 and after upgrade to version 2 you have to rewrite you configuration. And you can configure  serializer/desierializer to work with old xml. 

But I think that v2 should can:
1. Create xml with/without namespaces
2. Support Migrations,
3. Support Custom serializer,
4. Support Encrypt
5. Support object reference 
6. Optional: use auto properties
...
Do you agree with me?

**Comment by Mike-EEE** [comment]
> Do you agree with me?

💯%! 👏👏👏 :)

However. :)  just to **REALLY REALLY** sure.  Consider this.  The old XML looked like this:

`<Type type="Full.Type.Name" />`

New XML looks like:

`<ns:Type xmlns:ns="http://url/for/type" />`

This will also be breaking change, too.  Essentially, users will have to:

1. Reconfigure code, using new ConfigurationAPI
1. Rerun their code on their objects to create new XML.

Correct?

**Comment by wojtpl2** [comment]
They can configure 
var serializer = new ExtendedXmlSerializer();
for 
`<Type type="Full.Type.Name" />`
and they can:
var serializer = new ExtendedXmlSerializer(cfg => cfg.UseNamespaces());
for 
`<ns:Type xmlns:ns="http://url/for/type" />`

**Comment by wojtpl2** [comment]
In ExtendedXmlSerializer you have _config that has: 
`public bool Namespaces { get; set; }`

**Comment by Mike-EEE** [comment]
Ah. :)  I thought `UseNamespaces` was for consolidating namespaces up to the root element.

So:

```
<Root xmlns="ns1"><Item xmlns="ns2" /><Item xmlns="ns2" /></Root>
```

Becomes:
```
<Root xmlns="ns1" xmlns:ns2="ns2"><ns2:Item /><ns2:Item /></Root>
```

The problem with the `type=""` is that it is basically doing the work of `xmlns=""` which is confusing, and also leads to a lot of extra XML.  It is also responsible for a good amount of code right now in the `Legacy` folder.

My recommendation would be to enable and expect `<ns:Type xmlns:ns="http://url/for/type" />` to be the only format for v2.  This will reduce current code considerably.  Otherwise we will have to keep it to enable this.

**Comment by wojtpl2** [comment]
Standard XmlSerializer writes xml without namespaces. One of main feature is "Deserialization xml from standard XMLSerializer".
We have to read standard xml and write very similar xml. 

According to #24 in some cases users want to very simple xml without namespaces. I understand your arguments, but it is not good idea generate big xml for all situation. Eg.: Someone want to save configuration of application to xml with dictionary. He want change standard XmlSerializer to ExtendedXmlSerializer and he want very simple xml. He don't want big changes. If his xml is used in other tools, it can be very difficult to use ExtendedXmlSerializer instead of standard XmlSerialier.

Standard XmlSerializer works in the same way. If you want namespaces you can enable this function, eg.: http://stackoverflow.com/questions/2339782/xml-serialization-and-namespace-prefixes
We should go this way. What do you think? It is realy difficult to do?

**Comment by wojtpl2** [comment]
Of course we need one serializer. Switching between serializers it is not good idea.

**Comment by Mike-EEE** [comment]
> We have to read standard xml and write very similar xml

Agreed.  I like this part of ExtendedXmlSerializer. :)  However, ExtendedXmlSerializer is BETTER than XmlSerializer (in my world at least 😄) because it can be extended mightily.

So, to be sure, what I am suggesting is that we can still write without namespaces, as such:

```
<MyType xmlns="http://url/to/type" />
```

Instead of:

```
<MyType type="Full.Path.To.Type" />
```

(or)

```
<MyType exs:type="Full.Path.To.Type" xmlns:exs="http://https://github.com/wojtpl2/ExtendedXmlSerializer/v2" />
```

`xmlns=""` is standard XML and is what is written by XmlSerializer.  What I am saying is we should use that instead of `type=""` because it is more well-known and will remove **a lot** of the code I have in place now to make v1 work.

> but it is not good idea generate big xml for all situation

I am not sure if you meant it is not a good idea to generate big xml in ANY situation. :)  The idea is to make XML as small/concise as possible, as you know!

> We should go this way. What do you think? It is realy difficult to do?

Yes, I agree.  There are already components in place to do this:
https://github.com/Mike-EEE/ExtendedXmlSerializer/blob/feature/Deserializer/src/ExtendedXmlSerializer/ElementModel/Namespaces.cs

Just need to wire them up for v2. :)

**Comment by Mike-EEE** [comment]
So the point here is to remove `type=""` and replace with `xmlns=""` for v2.  However, this will break existing XML written in v1, which is the problem.

We can also delete `Legacy` and copy/paste all v1 code in there as well ([like this](https://github.com/wojtpl2/ExtendedXmlSerializer/tree/v2.0.0/test/ExtendedXmlSerializer.Performance.Tests/Legacy)), in case someone wants backwards compatibility as well.  What do you think?

**Comment by wojtpl2** [comment]
Ok now I understend you. 
I've read this http://www.w3schools.com/xml/xml_namespaces.asp, point "Default Namespaces".

Do you want to only rename "type" to "xmlns" without adding prefixes to elements? If yes I agree with you. But in this case we should think about migration old xml files. Maybe we should add options to configuration "Read old Type attribute as xmlns". But we can do it later.

**Comment by wojtpl2** [comment]
For me:
`<MyType xmlns="http://url/to/type" />`
looks better then
'<MyType exs:type="Full.Path.To.Type" xmlns:exs="http://https://github.com/wojtpl2/ExtendedXmlSerializer/v2" />'

**Comment by wojtpl2** [comment]
of course if you would like to keep 'Lagacy' for backward compatibility you can ;) But for me it is ok if we will be able to read old xml.

**Comment by Mike-EEE** [comment]
OK great!  Default namespaces are exactly what I am thinking of.  Every document and element has them.  This is one of the very many reasons why XML is so much better than JSON. ;)  But let's not tell the script kiddies this hee hee.

So to be clear here, I will:

1. Delete all files in the `Legacy` folder.
2. Copy all v1 code and paste in `Legacy` folder.
3. `[Obsolete]` all code in `Legacy`
4. Start working on v2 code. :)

Sound good?

I guess my only other question is: what does `UseNamespaces` do now?

**Comment by wojtpl2** [comment]
Do you think that we really need v1? what else will be different in version 2? 
1. xmlns insted of type attribute.
2?

**Comment by Mike-EEE** [comment]
Well this is for v1 XML.

So if you upgrade to v2, and we no longer support `type=""`, then when someone loads their document in v2, it will break (no longer load correctly).  If they want to migrate, they will have to load v1 DLL in their project **and** v2 DLL in their project, and do it that way.  This will be a pain. Putting v1 in `Legacy` allows them to have access to both in one DLL.  Make sense?

**Comment by Mike-EEE** [comment]
Also:

1. References will not work the same way.  there will be a `exs:reference` attribute now, and the ID will be a unique integer.  This way *any* object can be used and not have to reference a particular property ([Xaml does this](https://msdn.microsoft.com/en-us/library/ee795380%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396)).
1.  Because of `exs:reference`, `id=""` also goes away (simpler, faster).
1. `ver=""` becomes `exs:version=""`

Again, `Legacy` only stays around for v2.  We can delete it for v3. :)

**Comment by wojtpl2** [comment]
1, 2 I don't understand. How xml will be look now with reference and id?

Ok we can to do it like you wrote. Or we can support only deserializing of old version of xml in v2. You can choose simpler version. 
My requirements is: users should to be able deserializing of old xml and write in new format.

**Comment by Mike-EEE** [comment]
OK I haven't actually gotten to this yet, but it should look like this:

```
<Root>
	<SomeProperty exs:id="x34l38zq" />
	
	<AnotherProperty exs:reference="x34l38zq" />	
</Root>
```

So `id=""` _does_ stick around.  I was wrong.  It becomes `exs:id=""`.  What DOES go away is having to probe the `Configuration.Id` property.  Id's are now generated in v2.

**Comment by wojtpl2** [comment]
Ok.
Why in v2 id will be generated? If I configure typ like that:
            var serializer = new ExtendedXmlSerializer(cfg =>
            {
                cfg.ConfigureType<TestClassReference>().Property(p => p.Id).ObjectReference();
            });

and then I have:
var obj = new TestClassReference{ Id= 100};
than after serialization I will have:
<TestClassReference xmlns="..." exs:id="100"> 
or:
<TestClassReference xmlns="..." exs:id="x34l38zq">

**Comment by Mike-EEE** [comment]
OK I thought about this and there are actually two scenarios here:

1. References between POCOs (what I was thinking of).
2. References between entities with identity (what you're thinking of).

The first scenario would still cover the second, but it would be inefficient:

```
<TestClassReference xmlns="..." Id="100" exs:id="x34l38zq">
```
(btw `x34l38zq` is just a hash -- think [bit.ly](https://bitly.com/) URLs, we can make it shorter)

Here the id is translated twice (inefficient).  So in this case, when you use `ObjectReference`, it will hash a string derived from `100` (and also probably the entity type like you did in v1).

That will result in:

```
<TestClassReference xmlns="..." Id="100">

...

<TestClassReference xmlns="..." exs:reference="x34l38zq">
```

**Comment by wojtpl2** [comment]
I thought about it. I think that references between entities is good idea. But currently we don't have configuration for it. I think about class without Id. Eg:
```
Person{
public string Name {get; set;}
}
```

How about add function:
```
cfg =>
{
	cfg.ConfigureType<Person>().Entity()
};
```
Or do you want to automatically detect that this object will be used in many places in xml?

**Comment by Mike-EEE** [comment]
Goooood question. :)

To me, what this deals with is recursion in an entity graph.  A lot of serializers have options to determine what happens when recursion occurs:

- Throw an error
- Ignore
- Serialize (?  Doesn't that recurse?)

To me there is only one option, and that is serialize a reference pointer.  It's simpler all around and you don't have to worry about different approaches or case.

So I would say by default, an id is generated for an object (maybe just use the int from `GetHashCode`?) and is used to emit the id.  Otherwise, it will check to see if the `ObjectReference` method has been called on a property and use that instead.

How does that sound?

**Comment by wojtpl2** [comment]
But in this case you have to check all objects and all object will be have to exs:reference="x34l38zq".
During serialization you don't know if this object will be in xml in other place. You have to know which types are entity and which types are object with id.
It is also performance issue. For all object you will be call GetHashCode? Or not?

**Comment by Mike-EEE** [comment]
True. You can tell I haven't thought through this very much, just some ideas -- or maybe opinions is more like it, haha. :)  There will be overhead for this, so we should make it an optional call as you suggest, and then walk the graph -- much like how we do [with optimizing (or consolidating) xmlns namespaces](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/src/ExtendedXmlSerializer/Conversion/Xml/ObjectTypeWalker.cs) -- and strive to throw an error otherwise.

How about we introduce two Configuration API methods:

- Root-level configuration for every entity: `IExtendedXmlConfiguration.EnableReferences`
- Entity-level configuration for a particular entity: `IExtendedXmlTypeConfiguration<T>.EnableReferences(t => t.Id)`
- Additionally, if `IExtendedXmlTypeConfiguration<T>.EnableReferences()` is called without an entity Id expression, `exs:id="<hash>"` is generated/emitted.  Here we'll use/hash `GetHashCode` for the generated Id.

Thoughts?

**Comment by Mike-EEE** [comment]
Whoops!  Can you tell the coffee has not set in yet? :)  Yes, you also clearly state `IExtendedXmlPropertyConfiguration<T, TProperty>.Entity` above, as well.  Maybe we should make `IExtendedXmlTypeConfiguration<T>.EnableReferences` an extension method that shortcuts this.

**Comment by wojtpl2** [comment]
I've added methods:

1. For entity:
```
var serializer = new ExtendedXmlConfiguration().Create(
	cfg => cfg.ConfigureType<Person>().EnableReferences()
);
```

2. For Object with Id:
```
var serializer = new ExtendedXmlConfiguration().Create(
	cfg => cfg.ConfigureType<Person>().Property(p => p.Id).EnableReferences()
);
```

In back end you can get this information:
```
if (configuration.IsObjectReference) <-- is entity or object with id
{
	if (configuration.GetObjectId == null)
	{
		entity
	}
	else
	{
		var objectId = configuration.GetObjectId(o);
	}
}
```
If you would like to have two properties let me know. Eg configuration.IsEntity.
What do you think about this solution?

**Comment by Mike-EEE** [comment]
Great!  Looks like what we discussed.  My only feedback is for `GetObjectId`.  Is it possible to make this return an `int?`?

So:

```
if (configuration.IsObjectReference) <-- is entity or object with id
{
	var objectId = configuration.GetObjectId(o);
	if (objectId != null)
	{
		// id ...
	}
	else
	{
		// regular reference...
	}
}
```

If I understand it correctly. :)

**Comment by wojtpl2** [comment]
No.
configuration.GetObjectId - it is Func. For entity it is nul. So:
```
if (configuration.IsObjectReference) <-- is entity or object with id
{
	if ( configuration.GetObjectId != null)
	{
		// id ...
		var objectId = configuration.GetObjectId(o);
	}
	else
	{
		// regular reference...
	}
}
```

GetObjectId can't return int?. Eg I have Id that is GUID.
cfg => cfg.ConfigureType<Object>().Property(p => p.Id).EnableReferences()
where Id return GUID and in xml i want to have GUID.ToString()

**Comment by Mike-EEE** [comment]
Durp!  Yes, you are correct. 👼 ... I was thinking that it was *always* int.  No, that works fine!

**Pull request merged**
