### PR TITLE
Feature/Configuration API

### PR DESCRIPTION
**Pull request by Mike-EEE**
Alright!  Finally, some configuration API implementation!  This PR introduces most of the configuration API.  I still have to go through and implement some further functionality around members, but for the most part it is in there.

I will say that I am not 100% satisfied with it, but it is a starting point and we can improve it from here.  It relies heavily on extension methods, which work but I will have to put some time (if ever) to think of a better design.

Also, I took some time to rename classes that will be public:

`IExtendedXmlTypeConfiguration` -> `ITypeConfiguration`
`IExtendedXmlPropertyConfiguration` -> `IMemberConfiguration`
`IExtendedXmlConfiguration` -> `IExtendedConfiguration`

The idea here is in addition to less letters being used, it sets us up better for v3 if we decide to go w/ other formats beside XML (less inevitable breaking changes).  Please let me know if that is a problem.

### CODE REVIEW

**Comment by Mike-EEE** [comment]
For the most part v2 is feature complete and this should all now work.  Please give it a go (probably by using the samples project?) and let me know of any problems you find.

If you find something isn't working as expected, please create a failing test in the test project and commit it so that I can fetch and fix it.  Or anything you can suggest as a workflow. :)

**Comment by Mike-EEE** [comment]
Btw @wojtpl2 wasn't your birthday recently?  If so, happy (belated) birthday!  I know I was shooting to be feature complete by then, but I think I was a little late here.

**Comment by wojtpl2** [comment]
I'll try version 2 in may project. This project use references and has big xml's.

Thanks! Yes I had birthday.

**Comment by Mike-EEE** [comment]
Great.  That's good to hear, on both accounts. :)  I hope you don't run into any major problems using it!  Definitely interested in how it turns out for you.

**Comment by wojtpl2** [comment]
All work fine but I have small issue. I'll create new issue.

**Pull request merged**
